"""empty message

Revision ID: d6b88c51bcb4
Revises: f0bb7ca55a5a
Create Date: 2023-10-09 11:03:03.884958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b88c51bcb4'
down_revision = 'f0bb7ca55a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testing', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
